"""modified

Revision ID: 96fd414dab88
Revises: cf8c904bf8e1
Create Date: 2024-03-20 00:32:10.928063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96fd414dab88'
down_revision = 'cf8c904bf8e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ta_infos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blockYear', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('OtherThanHometown', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('GovtOffice', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ta_infos', schema=None) as batch_op:
        batch_op.drop_column('GovtOffice')
        batch_op.drop_column('OtherThanHometown')
        batch_op.drop_column('blockYear')

    # ### end Alembic commands ###
