"""modified database

Revision ID: 9f5b0a154afd
Revises: 8ca12395c0df
Create Date: 2024-03-13 10:21:59.467401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f5b0a154afd'
down_revision = '8ca12395c0df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('standingEarnedLeave', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('standingEarnedLeave')

    # ### end Alembic commands ###
