"""modified

Revision ID: cf8c904bf8e1
Revises: 9f5f697865c9
Create Date: 2024-03-19 23:34:29.412360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8c904bf8e1'
down_revision = '9f5f697865c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ltc_infos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blockYear', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ltc_infos', schema=None) as batch_op:
        batch_op.drop_column('blockYear')

    # ### end Alembic commands ###
